"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
import atexit
import logging
from appdirs import AppDirs
from pathlib import Path
import platform
import yaml

LOCAL_PORT = 3306
logger = logging.getLogger('dashboard.settings')
ssh_tunnel = None
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_root_config_yaml():
    config_path = BASE_DIR / 'config.yaml'
    if not config_path.exists():
        return {}
    with open(config_path, 'rt', encoding='utf-8') as f:
        data = yaml.safe_load(f) or {}
    return data if isinstance(data, dict) else {}


ROOT_CONFIG = _load_root_config_yaml()


def _start_ssh_tunnel_if_needed():
    global ssh_tunnel, LOCAL_PORT
    tunnel_cfg = ROOT_CONFIG.get('ssh_tunnel', {}) if isinstance(ROOT_CONFIG.get('ssh_tunnel', {}), dict) else {}
    local_node = str(tunnel_cfg.get('local_node', '')).strip()
    if local_node and platform.node() == local_node:
        return
    try:
        enabled = bool(tunnel_cfg.get('enabled', True))
        if not enabled:
            logger.info('SSH tunnel disabled by config.yaml ssh_tunnel.enabled=false')
            return

        from sshtunnel import SSHTunnelForwarder
        ssh_host = str(tunnel_cfg.get('host', '')).strip()
        ssh_port = int(tunnel_cfg.get('port', 22) or 22)
        ssh_username = 'root'
        if sys.platform == 'win32':
            ssh_key = str(tunnel_cfg.get('private_key_win', '')).strip()
        else:
            ssh_key = str(tunnel_cfg.get('private_key_linux', '')).strip()

        if not ssh_host or not ssh_key:
            logger.warning('SSH tunnel config missing required fields(host/private_key_[linux|win]), fallback to local mysql 3306')
            LOCAL_PORT = 3306
            return

        ssh_tunnel = SSHTunnelForwarder(
            (ssh_host, ssh_port),
            ssh_private_key=ssh_key,
            ssh_username=ssh_username,
            remote_bind_address=('127.0.0.1', 3306),
        )
        ssh_tunnel.start()
        LOCAL_PORT = ssh_tunnel.local_bind_port

        def _cleanup_tunnel():
            try:
                if ssh_tunnel:
                    ssh_tunnel.stop()
            except Exception:
                pass

        atexit.register(_cleanup_tunnel)
    except Exception as e:
        logger.warning('SSH tunnel start failed, fallback to local mysql 3306: %s', repr(e))
        LOCAL_PORT = 3306


_start_ssh_tunnel_if_needed()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m@zyyr4j=$8t4n^cj7!y4$yep&6-&kor6+zn8bk)ygfq*l2kk('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'panel.apps.PanelConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'quantdb',
        'HOST': '127.0.0.1',
        'USER': 'quant',
        'PASSWORD': '123456',
        'PORT': LOCAL_PORT
    },
}

app_dir = AppDirs('dashboard')
LOGGING = {
    'version': 1,
    'formatters': {'my_formatter': {'format': '%(asctime)s %(name)s [%(levelname)s] %(message)s'}},
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(app_dir.user_log_dir, 'dashboard.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'my_formatter',
        },
        'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'my_formatter'},
    },
    'loggers': {
        'panel': {'handlers': ['file', 'console'], 'level': 'DEBUG'},
        'dashboard.settings': {'handlers': ['file', 'console'], 'level': 'DEBUG'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "trader-dashboard-local-cache",
        "TIMEOUT": 3600 * 24,  # one day
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
LOGIN_URL = '/admin/'
LOGIN_REDIRECT_URL = '/'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
if sys.platform == 'linux':
    DEBUG = True
    ALLOWED_HOSTS = ['*']
